### ISSUE TITLE
jdk17 没有包访问权限，不支持nacos group功能

### ISSUE THREAD

**Issue by JerryRaf** [qiaolin-li/dubbo-desktop-manager#15]
Command failed: D:\Program Files\jdk17/bin/java -Dfile.encoding=utf-8 -jar D:\Program Files\dubbo-desktop\resources\app.asar.unpacked\jar\java-invoker.jar C:\Users\dubbo-desktop-manager\temp\java-invoke\cn.xxxxx.DemoService1716886841582.json
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
Caused by: java.lang.ExceptionInInitializerError
	at indi.qiaolin.ddm.invoker.Application.invoke(Application.java:60)
	at indi.qiaolin.ddm.invoker.Application.main(Application.java:46)
	... 8 more
Caused by: java.lang.IllegalStateException: Failed to create adaptive instance: java.lang.IllegalStateException: Can't create adaptive extension interface org.apache.dubbo.rpc.Protocol, cause: Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @5700d6b1
	at org.apache.dubbo.common.extension.ExtensionLoader.getAdaptiveExtension(ExtensionLoader.java:563)
	at org.apache.dubbo.config.ReferenceConfig.<clinit>(ReferenceConfig.java:104)
	... 10 more
Caused by: java.lang.IllegalStateException: Can't create adaptive extension interface org.apache.dubbo.rpc.Protocol, cause: Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @5700d6b1
	at org.apache.dubbo.common.extension.ExtensionLoader.createAdaptiveExtension(ExtensionLoader.java:971)
	at org.apache.dubbo.common.extension.ExtensionLoader.getAdaptiveExtension(ExtensionLoader.java:559)
	... 11 more
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @5700d6b1
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
	at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:199)
	at java.base/java.lang.reflect.Method.setAccessible(Method.java:193)
	at javassist.ClassPool.toClass2(ClassPool.java:1181)
	at javassist.ClassPool.toClass(ClassPool.java:1164)
	at javassist.CtClass.toClass(CtClass.java:1305)
	at org.apache.dubbo.common.compiler.support.JavassistCompiler.doCompile(JavassistCompiler.java:82)
	at org.apache.dubbo.common.compiler.support.AbstractCompiler.compile(AbstractCompiler.java:58)
	at org.apache.dubbo.common.compiler.support.AdaptiveCompiler.compile(AdaptiveCompiler.java:45)
	at org.apache.dubbo.common.extension.ExtensionLoader.createAdaptiveExtensionClass(ExtensionLoader.java:987)
	at org.apache.dubbo.common.extension.ExtensionLoader.getAdaptiveExtensionClass(ExtensionLoader.java:980)
	at org.apache.dubbo.common.extension.ExtensionLoader.createAdaptiveExtension(ExtensionLoader.java:969)
	... 12 more

解决办法 --add-opens
java.management/java.lang.management=ALL-UNNAMED
--add-opens
jdk.management/com.sun.management.internal=ALL-UNNAMED
--add-opens
java.management/sun.management=ALL-UNNAMED
--add-opens
java.base/java.time=ALL-UNNAMED
--add-opens
java.base/java.util.concurrent=ALL-UNNAMED
--add-opens
java.base/java.util.concurrent.locks=ALL-UNNAMED
--add-opens
java.base/java.security=ALL-UNNAMED
--add-opens
java.base/jdk.internal.loader=ALL-UNNAMED
--add-opens
java.management/com.sun.jmx.mbeanserver=ALL-UNNAMED
--add-opens
java.base/java.net=ALL-UNNAMED
--add-opens
java.base/sun.nio.ch=ALL-UNNAMED
--add-exports
java.base/sun.security.action=ALL-UNNAMED
--add-opens
java.base/java.lang=ALL-UNNAMED
--add-opens
java.base/java.math=ALL-UNNAMED
--add-opens
java.base/java.util=ALL-UNNAMED
--add-opens
java.base/java.text=ALL-UNNAMED
--add-opens
java.base/sun.util.calendar=ALL-UNNAMED 
jvm参数添加如上，帮忙找个地方加一下

**Comment by qiaolin-li** [comment]
好，我下个版本就支持上，你可以先下个JDK8，然后设置一下JDK的位置。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "qiaolin-li/dubbo-desktop-manager"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年5月28日(星期二) 下午5:06
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[qiaolin-li/dubbo-desktop-manager] jdk17 没有包访问权限，不支持nacos group功能 (Issue #15)





 
Command failed: D:\Program Files\jdk17/bin/java -Dfile.encoding=utf-8 -jar D:\Program Files\dubbo-desktop\resources\app.asar.unpacked\jar\java-invoker.jar C:\Users\dubbo-desktop-manager\temp\java-invoke\cn.xxxxx.DemoService1716886841582.json
 Exception in thread "main" java.lang.reflect.InvocationTargetException
 at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
 at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 at java.base/java.lang.reflect.Method.invoke(Method.java:568)
 at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
 at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
 at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
 at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
 Caused by: java.lang.ExceptionInInitializerError
 at indi.qiaolin.ddm.invoker.Application.invoke(Application.java:60)
 at indi.qiaolin.ddm.invoker.Application.main(Application.java:46)
 ... 8 more
 Caused by: java.lang.IllegalStateException: Failed to create adaptive instance: java.lang.IllegalStateException: Can't create adaptive extension interface org.apache.dubbo.rpc.Protocol, cause: Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @5700d6b1
 at org.apache.dubbo.common.extension.ExtensionLoader.getAdaptiveExtension(ExtensionLoader.java:563)
 at org.apache.dubbo.config.ReferenceConfig.(ReferenceConfig.java:104)
 ... 10 more
 Caused by: java.lang.IllegalStateException: Can't create adaptive extension interface org.apache.dubbo.rpc.Protocol, cause: Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @5700d6b1
 at org.apache.dubbo.common.extension.ExtensionLoader.createAdaptiveExtension(ExtensionLoader.java:971)
 at org.apache.dubbo.common.extension.ExtensionLoader.getAdaptiveExtension(ExtensionLoader.java:559)
 ... 11 more
 Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @5700d6b1
 at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
 at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
 at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:199)
 at java.base/java.lang.reflect.Method.setAccessible(Method.java:193)
 at javassist.ClassPool.toClass2(ClassPool.java:1181)
 at javassist.ClassPool.toClass(ClassPool.java:1164)
 at javassist.CtClass.toClass(CtClass.java:1305)
 at org.apache.dubbo.common.compiler.support.JavassistCompiler.doCompile(JavassistCompiler.java:82)
 at org.apache.dubbo.common.compiler.support.AbstractCompiler.compile(AbstractCompiler.java:58)
 at org.apache.dubbo.common.compiler.support.AdaptiveCompiler.compile(AdaptiveCompiler.java:45)
 at org.apache.dubbo.common.extension.ExtensionLoader.createAdaptiveExtensionClass(ExtensionLoader.java:987)
 at org.apache.dubbo.common.extension.ExtensionLoader.getAdaptiveExtensionClass(ExtensionLoader.java:980)
 at org.apache.dubbo.common.extension.ExtensionLoader.createAdaptiveExtension(ExtensionLoader.java:969)
 ... 12 more
 
解决办法 --add-opens
 java.management/java.lang.management=ALL-UNNAMED
 --add-opens
 jdk.management/com.sun.management.internal=ALL-UNNAMED
 --add-opens
 java.management/sun.management=ALL-UNNAMED
 --add-opens
 java.base/java.time=ALL-UNNAMED
 --add-opens
 java.base/java.util.concurrent=ALL-UNNAMED
 --add-opens
 java.base/java.util.concurrent.locks=ALL-UNNAMED
 --add-opens
 java.base/java.security=ALL-UNNAMED
 --add-opens
 java.base/jdk.internal.loader=ALL-UNNAMED
 --add-opens
 java.management/com.sun.jmx.mbeanserver=ALL-UNNAMED
 --add-opens
 java.base/java.net=ALL-UNNAMED
 --add-opens
 java.base/sun.nio.ch=ALL-UNNAMED
 --add-exports
 java.base/sun.security.action=ALL-UNNAMED
 --add-opens
 java.base/java.lang=ALL-UNNAMED
 --add-opens
 java.base/java.math=ALL-UNNAMED
 --add-opens
 java.base/java.util=ALL-UNNAMED
 --add-opens
 java.base/java.text=ALL-UNNAMED
 --add-opens
 java.base/sun.util.calendar=ALL-UNNAMED
 jvm参数添加如上，帮忙找个地方加一下

**Comment by qiaolin-li** [comment]
不好意思，我今天才看到.....微信绑定的邮箱过期了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "992004863"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年5月31日(星期五) 上午10:55
***@***.***&gt;;

主题:&nbsp;回复：[qiaolin-li/dubbo-desktop-manager] jdk17 没有包访问权限，不支持nacos group功能 (Issue #15)



好，我下个版本就支持上，你可以先下个JDK8，然后设置一下JDK的位置。




------------------ 原始邮件 ------------------
发件人:                                                                                                                        "qiaolin-li/dubbo-desktop-manager"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年5月28日(星期二) 下午5:06
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[qiaolin-li/dubbo-desktop-manager] jdk17 没有包访问权限，不支持nacos group功能 (Issue #15)





 
Command failed: D:\Program Files\jdk17/bin/java -Dfile.encoding=utf-8 -jar D:\Program Files\dubbo-desktop\resources\app.asar.unpacked\jar\java-invoker.jar C:\Users\dubbo-desktop-manager\temp\java-invoke\cn.xxxxx.DemoService1716886841582.json
 Exception in thread "main" java.lang.reflect.InvocationTargetException
 at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
 at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 at java.base/java.lang.reflect.Method.invoke(Method.java:568)
 at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
 at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
 at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
 at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
 Caused by: java.lang.ExceptionInInitializerError
 at indi.qiaolin.ddm.invoker.Application.invoke(Application.java:60)
 at indi.qiaolin.ddm.invoker.Application.main(Application.java:46)
 ... 8 more
 Caused by: java.lang.IllegalStateException: Failed to create adaptive instance: java.lang.IllegalStateException: Can't create adaptive extension interface org.apache.dubbo.rpc.Protocol, cause: Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @5700d6b1
 at org.apache.dubbo.common.extension.ExtensionLoader.getAdaptiveExtension(ExtensionLoader.java:563)
 at org.apache.dubbo.config.ReferenceConfig.(ReferenceConfig.java:104)
 ... 10 more
 Caused by: java.lang.IllegalStateException: Can't create adaptive extension interface org.apache.dubbo.rpc.Protocol, cause: Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @5700d6b1
 at org.apache.dubbo.common.extension.ExtensionLoader.createAdaptiveExtension(ExtensionLoader.java:971)
 at org.apache.dubbo.common.extension.ExtensionLoader.getAdaptiveExtension(ExtensionLoader.java:559)
 ... 11 more
 Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @5700d6b1
 at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
 at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
 at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:199)
 at java.base/java.lang.reflect.Method.setAccessible(Method.java:193)
 at javassist.ClassPool.toClass2(ClassPool.java:1181)
 at javassist.ClassPool.toClass(ClassPool.java:1164)
 at javassist.CtClass.toClass(CtClass.java:1305)
 at org.apache.dubbo.common.compiler.support.JavassistCompiler.doCompile(JavassistCompiler.java:82)
 at org.apache.dubbo.common.compiler.support.AbstractCompiler.compile(AbstractCompiler.java:58)
 at org.apache.dubbo.common.compiler.support.AdaptiveCompiler.compile(AdaptiveCompiler.java:45)
 at org.apache.dubbo.common.extension.ExtensionLoader.createAdaptiveExtensionClass(ExtensionLoader.java:987)
 at org.apache.dubbo.common.extension.ExtensionLoader.getAdaptiveExtensionClass(ExtensionLoader.java:980)
 at org.apache.dubbo.common.extension.ExtensionLoader.createAdaptiveExtension(ExtensionLoader.java:969)
 ... 12 more
 
解决办法 --add-opens
 java.management/java.lang.management=ALL-UNNAMED
 --add-opens
 jdk.management/com.sun.management.internal=ALL-UNNAMED
 --add-opens
 java.management/sun.management=ALL-UNNAMED
 --add-opens
 java.base/java.time=ALL-UNNAMED
 --add-opens
 java.base/java.util.concurrent=ALL-UNNAMED
 --add-opens
 java.base/java.util.concurrent.locks=ALL-UNNAMED
 --add-opens
 java.base/java.security=ALL-UNNAMED
 --add-opens
 java.base/jdk.internal.loader=ALL-UNNAMED
 --add-opens
 java.management/com.sun.jmx.mbeanserver=ALL-UNNAMED
 --add-opens
 java.base/java.net=ALL-UNNAMED
 --add-opens
 java.base/sun.nio.ch=ALL-UNNAMED
 --add-exports
 java.base/sun.security.action=ALL-UNNAMED
 --add-opens
 java.base/java.lang=ALL-UNNAMED
 --add-opens
 java.base/java.math=ALL-UNNAMED
 --add-opens
 java.base/java.util=ALL-UNNAMED
 --add-opens
 java.base/java.text=ALL-UNNAMED
 --add-opens
 java.base/sun.util.calendar=ALL-UNNAMED
 jvm参数添加如上，帮忙找个地方加一下

**Comment by qiaolin-li** [comment]
![image](https://github.com/qiaolin-li/dubbo-desktop-manager/assets/32925394/277f848b-c4f2-45f5-bf44-4f8deea828ef)

请问你们用的nacos group是指的第一个还是第二个啊！

**Comment by JerryRaf** [comment]
> ![image](https://private-user-images.githubusercontent.com/32925394/336054601-277f848b-c4f2-45f5-bf44-4f8deea828ef.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc0NjYxMjIsIm5iZiI6MTcxNzQ2NTgyMiwicGF0aCI6Ii8zMjkyNTM5NC8zMzYwNTQ2MDEtMjc3Zjg0OGItYzRmMi00NWY1LWJmNDQtNGY4ZGVlYTgyOGVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA0VDAxNTAyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMwZWViNDY3NTNlZDJhNzkyZWEwMjM5ZDMxMTJiNWIxMGI2NzQ5NjdmZGRhNDFmMzg5NzZhYjA1MTA2YTFjNjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.C1wHYvECeQvXHMXijG-4hblSwhzub2rOD442zme1oB0)
> 
> 请问你们用的nacos group是指的第一个还是第二个啊！

第二个，有时候不会用默认的group，，请问元数据为什么读取不出来，nacos都有配置dubbo元数据信息的，配置中心也有看到元数据信息

**Comment by qiaolin-li** [comment]
你是用的哪个版本的nacos啊，我上次发现高版本的nacos像有问题，到时候我测试下

**Comment by qiaolin-li** [comment]
昨天晚上我想设置这个分组名称，但是没设置成功，估计是dubbo版本有问题，今晚我再试试，JDK17的问题应该是搞定了

**Comment by JerryRaf** [comment]
> 你是用的哪个版本的nacos啊，我上次发现高版本的nacos像有问题，到时候我测试下

nacos-client：2.2.1  nacos-server：2.2.0  ,jdk17 ,springboot:3.2.5   ,dubbo:3.2.12

**Comment by JerryRaf** [comment]
> 昨天晚上我想设置这个分组名称，但是没设置成功，估计是dubbo版本有问题，今晚我再试试，JDK17的问题应该是搞定了

分组到无所谓，估计的跟dubbo的底层底层代码脱不了关系，大不了用默认的。但是这个元数据没有，导致不能把方法参数映射出来，，

**Comment by JerryRaf** [comment]
![image](https://github.com/qiaolin-li/dubbo-desktop-manager/assets/7145259/3c3247c3-36f2-4905-a77c-cc930b61dde3)

![image](https://github.com/qiaolin-li/dubbo-desktop-manager/assets/7145259/db91ad3d-dc69-4baa-be69-38c0a0b2dbf2)


![image](https://github.com/qiaolin-li/dubbo-desktop-manager/assets/7145259/e7b5ce07-1829-435c-bb57-b49493104f9b)

![image](https://github.com/qiaolin-li/dubbo-desktop-manager/assets/7145259/95e7e118-484a-49cd-a430-53867a4d3c98)


dubbo:
 application:
   name: ${spring.application.name}
   qos-enable: true
  #  protocol: dubbo
   #provider注册模式，可选值 interface(接口级)、instance(应用级)、all，默认是all(双注册)
   register-mode: interface
   metadata-type: remote
   serialize-check-status: DISABLE
   check-serializable: false
 registry:
  #&group=dubbo
   address: nacos://${nacos.addr}?namespace=${nacos.namespace}
   protocol: dubbo
   timeout: 2000
   register-mode: interface
   file: ../registry/${spring.application.name}
   use-as-metadata-center: true
   use-as-config-center: true
   metadata-report: 
    address: nacos://${nacos.addr}?namespace=${nacos.namespace}
   config-center: 
    address: nacos://${nacos.addr}?namespace=${nacos.namespace}
 protocol:
   name: dubbo
   port: 28082
   corethreads: 10 #核心线程数
   serialization: hessian2
 provider:
   loadbalance: roundrobin
   actives: 0 #consumer，每方法最大并发调用数
   connections: 10 #consumer，最大并发调用数
   accepts: 0 #最大可以接受的连接数
   threadpool: cached
   threads: 300 #最大线程数（队列为0是阻塞对列，该值没用）
   alive: 5000 #非核心线程存活时间
   queues: 0 #阻塞对列
   timeout: 60000
   executes: 0 #提供者,每方法最大并发调用数
   retries: 0
   filter: -exception
 consumer:
   check: false
   retries: 0

**Comment by qiaolin-li** [comment]
你尝试着给暴露的dubbo接口加个版本看看
@Service(version = "1.0.0")

**Comment by qiaolin-li** [comment]
http://127.0.0.1:8848/nacos/v1/cs/configs?dataId=${这里填这个dataId}&group=dubbo
你用这个地址，看看能不能查到数据

**Comment by JerryRaf** [comment]
![image](https://github.com/qiaolin-li/dubbo-desktop-manager/assets/7145259/aba22830-382f-4b7a-bedb-c2a1a2b1a910)

![image](https://github.com/qiaolin-li/dubbo-desktop-manager/assets/7145259/a8899f13-c624-42a0-928c-f4a3687f9f4f)

**Comment by JerryRaf** [comment]
![image](https://github.com/qiaolin-li/dubbo-desktop-manager/assets/7145259/91a1e456-57a5-4be6-8c06-8402c3e915fb)
有这个符号就不能获取到 ，其它的配置都是可以的

**Comment by qiaolin-li** [comment]
感觉有bug一样，哪个带1.0.0的能获取吗
![image](https://github.com/qiaolin-li/dubbo-desktop-manager/assets/32925394/95fc7647-a54d-46e2-9104-152e13e99087)

**Comment by JerryRaf** [comment]
都不能获取，跟这些都没关系了，我是自己新增一个简单的配置，然后带这种分割符号，跟不带做的实验

**Comment by qiaolin-li** [comment]
换个nacos-server-2.0.3试试，之前我用2.3.2也遇到过，估计是nacos的bug

**Comment by qiaolin-li** [comment]
你尝试在url上加入参数`show=all`，看看有没有数据
http://127.0.0.1:8848/nacos/v1/cs/configs?show=all&dataId=org.apache.dubbo.demo.DemoService:1:1:provider:dubbo-demo-annotation-provider&group=DEFAULT_GROUP

**Comment by JerryRaf** [comment]
> 你尝试在url上加入参数`show=all`，看看有没有数据 http://127.0.0.1:8848/nacos/v1/cs/configs?show=all&dataId=org.apache.dubbo.demo.DemoService:1:1:provider:dubbo-demo-annotation-provider&group=DEFAULT_GROUP

能发一下你这边的全部dubbo nacos配置么，换个nacos-server-2.0.3试试，之前我用2.3.2也遇到过，估计是nacos的bug你说的这个是对的，但是 用老版本nacos也没法弄出来元数据，元数据到底是怎么配置的

**Comment by qiaolin-li** [comment]
我这边都是我自己搞得demo，没有什么参考意义，你说的jdk版本问题和nacos的问题我应该是修复好了，你使用下最新的1.0.9版本看看

**Comment by qiaolin-li** [comment]
下载地址：https://github.com/qiaolin-li/dubbo-desktop-manager/releases/tag/v1.0.9
